[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

#[[patches]]
#[patches.pattern]
#target = "game.lua"
#pattern = '''
#G.SPLASH_LOGO = Sprite(0, 0, 
#    13*SC_scale, 
#    13*SC_scale*(G.ASSET_ATLAS["balatro"].py/G.ASSET_ATLAS["balatro"].px),
#    G.ASSET_ATLAS["balatro"], {x=0,y=0})
#'''
#position = "at"
#payload = '''
#    local poke_logo = pokermon_config.pokemon_aprilfools and "poke_smeargle_logo" or "poke_logo"
#    G.SPLASH_LOGO = Sprite(0, 0, 
#        13/333*389*SC_scale, 
#        13/333*389*SC_scale*(G.ASSET_ATLAS[poke_logo].py/G.ASSET_ATLAS[poke_logo].px),
#        G.ASSET_ATLAS[poke_logo], {x=0.0,y=0})
#'''
#match_indent = true
#overwrite = true


# Replace start menu card with wobbuffet
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''
local replace_card = Card(self.title_top.T.x, self.title_top.T.y, 1.2*G.CARD_W*SC_scale, 1.2*G.CARD_H*SC_scale, G.P_CARDS.S_A, G.P_CENTERS.c_base)
'''
position = "at"
payload = '''
local replace_card = Card(self.title_top.T.x, self.title_top.T.y, 1.2*G.CARD_W*SC_scale, 1.2*G.CARD_H*SC_scale, G.P_CARDS.empty, G.P_CENTERS.j_insc_squirrel)
'''
match_indent = true